### ISSUE TITLE
Upgrade Plausible from 2.0.0 to 2.1.0

### ISSUE THREAD

**Issue by vBohu** [railwayapp-templates/plausible#10]
Most importantly Plausible 2.1 allows for .csv data import+export.

Upgrading from 2.0 (latest DockerHub version) to 2.1 is simple: https://github.com/plausible/analytics/releases/tag/v2.1.0

Pretty much just change the docker image from
plausible/analytics:v2.0.0
to
ghcr.io/plausible/community-edition:v2.1.0

A possibility to update existing Railway Deployments would also be great!

**Comment by MykalMachon** [comment]
Hey @vBohu, Thank you for submitting an issue. 

I've updated the template to point at the new community edition image and verified that it'll work. I'm not sure what the railway story is for updating existing railway deployments but from what I can tell all you'd need to do is 

- Set an environment variable called `TOTP_VAULT_KEY` that's value is set to the result of `${{secret(43, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/")}}=`
- Update your environment variable called `SECRET_KEY_BASE` and set the value to the result of `${{secret(86, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/")}}==`
- Add an environment variable called `ECTO_IPV6` and set it to true 
- Update your environment variable called `DATABASE_URL` and set it to `${{Postgres.DATABASE_PRIVATE_URL}}`
- Change your source image to the image you linked above. If you set the image to `ghcr.io/plausible/community-edition:v2` it will automatically update to any new version that has new features without introducing breaking changes.

Let me know if you have any issues!
