### ISSUE TITLE
custom subdomain login 403 error

### ISSUE THREAD

**Issue by JugglerX** [railwayapp-templates/plausible#11]
Hi, thank you very much for creating this template. It worked flawlessly and I was able to get a self hosted instance up and running. 

I've added a custom subdomain, which is resolving, but when I login i experience a 403 error.

Other than adding he subdomain in Railway under "public networking" and adding the CNAME to my DNS is there anything else I need to do?

**Comment by MykalMachon** [comment]
Hi @JugglerX, sorry for the delay in getting back to you here! I somehow missed this issue when it came in.
I just went through the process and it worked all the way through and did the same steps you mentioned. Do you mind: 

1. Sharing anything in your logs that seems to point at an error in the service
2. Clearing the cache for the original site as well as the new site (I doubt this is the issue but worth a shot).

If you figure it out, do you mind sharing the solution here?

**Comment by MykalMachon** [comment]
Closing as stale
