### ISSUE TITLE
Incorrect Country

### ISSUE THREAD

**Issue by henrikruscon** [railwayapp-templates/plausible#12]
Every single visiting country is US, is this a known issue?

**Comment by MykalMachon** [comment]
@henrikruscon hey, I was not seeing this on my instance. Did you sort out what the problem was? If so, do you mind sharing here.

**Comment by henrikruscon** [comment]
> @henrikruscon hey, I was not seeing this on my instance. Did you sort out what the problem was? If so, do you mind sharing here. 

Ended up being caused by CloudFlare proxy being enabled, basically replaces the geolocation with the proxies location. Simply turning it off solves the issue.

Thanks for checking.
