### ISSUE TITLE
Broken deployment

### ISSUE THREAD

**Issue by LukasZubal** [railwayapp-templates/plausible#13]
It seem the deployment is somehow broken on railway. Throbbers does not dissapear :(
<img width="592" alt="image" src="https://github.com/user-attachments/assets/aa8e3dd4-b280-441a-b13c-bb1d82d4917d">

**Comment by MykalMachon** [comment]
Hi @LukasZubal,
I'll look into this but it may be a platform issue with Railway.
I'll try doing a deploy right now.

**Comment by MykalMachon** [comment]
Hi @LukasZubal,
I was just able to deploy and configure a new instance of Plausible via Railway. 
This might be an issue with your account or cache in your web browser. I would recommend [reaching out to Railway directly on either the forum](https://help.railway.app/) or their discord

**Comment by LukasZubal** [comment]
Yes,bad account. Thank you for quick response. Lukas
