### ISSUE TITLE
nc: bad address 'clickhouse.railway.internal'

### ISSUE THREAD

**Issue by pedroaraujo74** [railwayapp-templates/plausible#6]
Getting `nc: bad address 'clickhouse.railway.internal'` when trying to access the main the plausible URL. Without modifying any vars

**Comment by MykalMachon** [comment]
Hi @pedroaraujo74, I've noticed that I occasionally get this error from the Plausible service as well but everything operates as normal despite it.
Have you tried setting up plausible as normal? If so, is there some other error or context you can share? or is it operating as normal?

**Comment by MykalMachon** [comment]
Closing this as no response and as far as I can tell this is not an issue that affects the service or it's performance 🙂
Feel free to re-open at a later date with more details @pedroaraujo74
