### ISSUE TITLE
Private networking is not working

### ISSUE THREAD

**Issue by dane-stevens** [railwayapp-templates/plausible#9]
On startup: plausible service cannot connect to clickhouse.

Need to add environment variable to all services: `ENABLE_ALPINE_PRIVATE_NETWORKING=true`

This resolves the private networking bug described here: https://docs.railway.app/guides/private-networking#workaround-for-alpine-based-images

**Comment by MykalMachon** [comment]
Hey @dane-stevens , 
I've updated the template to the newest open-source version of Plausible and made the networking private by default across all resources. If you redeploy now you can check it out and then copy the required settings over to your existing environment if needed! 

Thanks for filing an issue with steps to resolution.
